name: AWS DevOps CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with pylint
        run: |
          pylint --disable=C0111,C0103,C0303,C0330,C0326 --max-line-length=120 scripts/*.py lambda/*.py

      - name: Run tests
        run: |
          pytest -xvs

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

  build:
    runs-on: ubuntu-latest
    needs: [test, terraform-validate]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Lambda package
        run: |
          mkdir -p build
          cp -r lambda/* build/
          cd build
          zip -r ../lambda_function.zip .

      - name: Upload Lambda package
        uses: actions/upload-artifact@v3
        with:
          name: lambda-package
          path: lambda_function.zip
